# Generated by Django 4.2.6 on 2023-10-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0002_feedback_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='title',
            new_name='theme',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
    ]
